version : '3.8'

services:
  db:
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chrono69
      POSTGRES_DB: db_pos
    
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 54320:5432